# Generated by Django 6.1 on 2026-09-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dailyrecord',
            constraint=models.UniqueConstraint(fields=('business', 'date'), name='unique_business_daily_record'),
        ),
    ]
