# Generated by Django 6.1 on 2026-09-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_dailyrecord_unique_business_daily_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='nozzle_a_closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='nozzle_b_closing',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
