# Generated by Django 6.1 on 2026-09-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_alter_dailyrecord_nozzle_a_closing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='cash_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='transfers_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
