# Generated by Django 6.1 on 2026-09-09 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_dailyrecord_cash_collected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(default='litres', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FuelDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_date', models.DateField()),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('supplier', models.CharField(max_length=150)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('physical_tank_reading', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_deliveries', to='station.business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='station.product')),
            ],
        ),
    ]
